/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by @tanstack/router-plugin on `bun dev` or `bun build`.
// Do not edit manually — changes will be overwritten.

import { createFileRoute, createRootRoute } from '@tanstack/react-router'

import { Route as rootRoute } from './routes/__root'
import { Route as IndexRoute } from './routes/index'
import { Route as ChatRoute } from './routes/chat'

const routeTree = rootRoute.addChildren([IndexRoute, ChatRoute])

export { routeTree }
